function makemeSticky(e){function t(){var e=s.getBoundingClientRect();e.top<0?(n.className=a+" makesticking",n.style.width=i+"px"):n.className=a}var n=document.getElementById(e),s=document.createElement("div");n.parentNode.insertBefore(s,n);var i=n.offsetWidth,a=n.className+" makesticky";window.addEventListener("scroll",t,!1)}makemeSticky("Followers1");
$(document).ready(function(){$("#showparser").click(function(){$("#parser").slideToggle("slow")})});
$(document).ready(function(){$("#emotext").click(function(){$("#emoshow").slideToggle("normal")})});
function convert(){var ele1 = document.getElementById("somewhere");var replaced;replaced = ele1.value;replaced = replaced.replace(/&/ig, "&amp;");replaced = replaced.replace(/</ig, "&lt;");replaced = replaced.replace(/>/ig, "&gt;");replaced = replaced.replace(/"/ig, "&quot;");replaced = replaced.replace(/&#177;/ig, "&plusmn;");replaced = replaced.replace(/&#169;/ig, "&copy;");replaced = replaced.replace(/&#174;/ig, "&reg;");replaced = replaced.replace(/ya'll/ig, "ya'll");ele1.value = replaced;};
$(function(){$(".menu-notif").on("click",function(){$(".notif-blanter").addClass("active").find(".search").focus()});$(".notif-blanter").on("click",function(){$(this).find(".search").focus()});$(".notif-close").on("click",function(){$(".notif-blanter").removeClass("active")})});
window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":"","theme":"light-bottom"};
(function(){var e=document.createElement("script");e.async=true;e.type="text/javascript";e.src="https://yourjavascript.com/8191175451/cookieconsent.js";(document.getElementsByTagName("HEAD")[0]||document.getElementsByTagName("BODY")[0]).appendChild(e)})();
$(".post-author img").each(function(){$(this).attr("src",$(this).attr("src").replace(/\/s[0-9]+(\-c)?\//,"/s40-c/"))});
$(".popular-posts img").each(function(){$(this).attr("src",$(this).attr("src").replace(/\/w170-h170+(\-p-k-no-nu)?\//,"/w170-h170/"))});
